apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
  # Thses are replica set labels
  labels:
    purpose: toleration-demo
    project: roboshop
spec: 
  replicas: 1
  selector:
    # These labels are used to select pods
    matchLabels:
      # purpose: dp-demo
      purpose : headless-svc-demo
      project: roboshop
  # Pod definition    
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose : toleration-demo
        project: roboshop
    spec: 
      containers: 
      - name: nginx
        image: nginx:latest