apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      # HARD RULE
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c
          # - key: disktype
          #   operator: In
          #   values:
          #   - ssd
      # SOFT RULE      
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop

      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon   
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always


 # SOFT RULE & HARD RULE WILL WORK SAME AVAILABILITY ZONE   example 2 nodes like us-east 1c 
